# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Docker Meta'
description: "GitHub Action to extract metadata (tags, labels) for Docker"
author: 'crazy-max'
branding:
  color: 'blue'
  icon: 'layers'

inputs:
  images:
    description: 'List of Docker images to use as base name for tags'
    required: true
  tag-sha:
    description: 'Add git short SHA as Docker tag'
    default: 'false'
    required: false
  tag-edge:
    description: 'Enable edge branch tagging'
    default: 'false'
    required: false
  tag-edge-branch:
    description: 'Branch that will be tagged as edge (default repo.default_branch)'
    required: false
  tag-coerce-tag:
    description: 'Coerces Git tag to semver if possible using Handlebars template'
    required: false
  tag-schedule:
    description: 'Handlebars template to apply to schedule tag'
    default: 'nightly'
    required: false
  sep-tags:
    description: 'Separator to use for tags output (default \n)'
    required: false
  sep-labels:
    description: 'Separator to use for labels output (default \n)'
    required: false
  github-token:
    description: 'GitHub Token as provided by secrets'
    default: ${{ github.token }}
    required: true

outputs:
  version:
    description: 'Generated Docker image version'
  tags:
    description: 'Generated Docker tags'
  labels:
    description: 'Generated Docker labels'

runs:
  using: 'node12'
  main: 'dist/index.js'
