# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Docker Metadata action'
description: "GitHub Action to extract metadata (tags, labels) for Docker"
author: 'docker'
branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  context:
    description: 'Where to get context data. Allowed options are "workflow"  (default), "git".'
    default: "workflow"
    required: true
  images:
    description: 'List of Docker images to use as base name for tags'
    required: false
  tags:
    description: 'List of tags as key-value pair attributes'
    required: false
  flavor:
    description: 'Flavors to apply'
    required: false
  labels:
    description: 'List of custom labels'
    required: false
  annotations:
    description: 'List of custom annotations'
    required: false
  sep-tags:
    description: 'Separator to use for tags output (default \n)'
    required: false
  sep-labels:
    description: 'Separator to use for labels output (default \n)'
    required: false
  sep-annotations:
    description: 'Separator to use for annotations output (default \n)'
    required: false
  bake-target:
    description: 'Bake target name (default docker-metadata-action)'
    required: false
  github-token:
    description: 'GitHub Token as provided by secrets'
    default: ${{ github.token }}
    required: true

outputs:
  version:
    description: 'Generated Docker image version'
  tags:
    description: 'Generated Docker tags'
  labels:
    description: 'Generated Docker labels'
  annotations:
    description: 'Generated annotations'
  json:
    description: 'JSON output of tags and labels'
  bake-file-tags:
    description: 'Bake definition file with tags'
  bake-file-labels:
    description: 'Bake definition file with labels'
  bake-file-annotations:
    description: 'Bake definition file with annotations'
  bake-file:
    description: 'Bake definition file with tags and labels'

runs:
  using: 'node20'
  main: 'dist/index.js'
