name: test

on:
  push:
    branches:
      - 'master'
      - 'releases/v*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'master'
      - 'releases/v*'
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Validate
        uses: docker/bake-action@v1
        with:
          targets: validate
      -
        name: Test
        uses: docker/bake-action@v1
        with:
          targets: test
      -
        name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/clover.xml
